In [2]:
import sqlite3
import pandas as pd

# Load datasets
athletes = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/athlete_events.csv")
regions = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/noc_regions.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
sales = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

# Connect to SQLite in-memory DB
conn = sqlite3.connect(":memory:")

# Write DataFrames to SQL tables
athletes.to_sql("athletes_table", conn, index=False, if_exists="replace")
regions.to_sql("regions_table", conn, index=False, if_exists="replace")
sales.to_sql("sales_table", conn, index=False, if_exists="replace")

4622

# Section 1
Use the athletes, regions, and sales datasets.

The athletes dataset:

1. Count the total number of medals won by each country and show the top 5.

2. Calculate the average age of athletes who won a Gold medal.

3. How many distinct events are there in each sport?

4. Show all athletes from the United States (NOC = 'USA').

5. Count how many medals were awarded each year.

6. Find all athlete records where height or weight is missing.

In [3]:
 # Total number of medals won by each country showing top 5
print("Athletes Table:")
pd.read_sql(
    """SELECT count(Medal) as total_medals, NOC
    FROM athletes_table
    GROUP BY NOC
    ORDER BY total_medals DESC
    LIMIT 5
    """, conn)
# print("Regions Table:")
# pd.read_sql("SELECT * FROM regions_table LIMIT 5", conn)
# print("Sales Table:")
# pd.read_sql("SELECT * FROM sales_table LIMIT 5", conn)

Athletes Table:

   total_medals  NOC
0          5637  USA
1          2503  URS
2          2165  GER
3          2068  GBR
4          1777  FRA

In [4]:
# Average age of atheletes who won GOLD medals
print("Average age of athletes who won GOLD medals:")
pd.read_sql(
    """SELECT AVG(Age) as average_age
    FROM athletes_table
    WHERE Medal = 'Gold'
    """, conn)

Average age of athletes who won GOLD medals:

   average_age
0    25.901013

In [5]:
# How many distinct events are there in each sport
print("Number of distinct events in each sport:")
pd.read_sql(
    """SELECT Sport, COUNT(DISTINCT Event) as distinct_events
    FROM athletes_table
    GROUP BY Sport
    """, conn)

Number of distinct events in each sport:

               Sport  distinct_events
0        Aeronautics                1
1      Alpine Skiing               10
2           Alpinism                1
3            Archery               29
4   Art Competitions               29
..               ...              ...
61        Tug-Of-War                1
62        Volleyball                2
63        Water Polo                2
64     Weightlifting               21
65         Wrestling               30

[66 rows x 2 columns]

In [ ]:
# All atheletes from NOC="USA"
print("All athletes from NOC='USA':")
pd.read_sql(
    """SELECT * 
    FROM athletes_table
    WHERE NOC = 'USA'
    """, conn
)

All athletes from NOC='USA':

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
1,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
2,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
3,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
4,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18848,135458,Rami Zur,M,27.0,175.0,77.0,United States,USA,2004 Summer,2004,Summer,Athina,Canoeing,"Canoeing Men's Kayak Doubles, 500 metres",NaN
18849,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 500 metres",NaN
18850,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",NaN
18851,135543,"Victor Andrew ""Vic"" Zwolak",M,25.0,175.0,64.0,United States,USA,1964 Summer,1964,Summer,Tokyo,Athletics,"Athletics Men's 3,000 metres Steeplechase",NaN
18852,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN

In [8]:
# Count how many medals were awarded each year
pd.read_sql(
    """SELECT Year, COUNT(Medal) AS total_medals
    FROM athletes_table
    GROUP BY Year
    """, conn
)

    Year  total_medals
0   1896           143
1   1900           604
2   1904           486
3   1906           458
4   1908           831
5   1912           941
6   1920          1308
7   1924           962
8   1928           823
9   1932           739
10  1936          1025
11  1948           987
12  1952          1033
13  1956          1043
14  1960          1058
15  1964          1215
16  1968          1256
17  1972          1414
18  1976          1531
19  1980          1602
20  1984          1698
21  1988          1845
22  1992          2030
23  1994           331
24  1996          1842
25  1998           440
26  2000          2004
27  2002           478
28  2004          2001
29  2006           526
30  2008          2048
31  2010           520
32  2012          1941
33  2014           597
34  2016          2023

In [ ]:
# All missing height or weight records for athletes
pd.read_sql(
    """SELECT *
    FROM athletes_table
    WHERE Height IS NULL OR Weight IS NULL
""", conn
)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
1,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
2,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
3,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN
4,10,"Einar Ferdinand ""Einari"" Aalto",M,26.0,NaN,NaN,Finland,FIN,1952 Summer,1952,Summer,Helsinki,Swimming,Swimming Men's 400 metres Freestyle,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64258,135539,Marius Edmund Zwiller,M,18.0,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 200 metres Breaststroke,NaN
64259,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
64260,135542,Werner Zwingli,M,29.0,NaN,NaN,Switzerland,SUI,1956 Winter,1956,Winter,Cortina d'Ampezzo,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
64261,135552,Jan (Johann-) Zybert (Siebert-),M,20.0,NaN,NaN,Poland,POL,1928 Summer,1928,Summer,Amsterdam,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
64262,135561,Frantiek Zyka,M,26.0,NaN,NaN,Czechoslovakia,TCH,1928 Summer,1928,Summer,Amsterdam,Athletics,Athletics Men's Marathon,NaN

The sales dataset: where necessary, use the key word CAST to remove the $ sign from the item_price

7. Replace the missing height with the average athlete height.

8. Return total sales value per item.

9. Show the top 5 records with the highest item_price.

10. How many unique customer orders are there? (Assume each order_id is a customer.)

In [ ]:
# Replace missing height with the average athlete height
athletes_copy = athletes.copy()
avg_height = athletes_copy['Height'].mean()

print(f"Before fillna")
null = athletes['Height'].isna().to_list()
print(f"Null values = {null.count(True)}")

athletes_copy['Height'].fillna(value=avg_height)

print("After fillna")
null = athletes['Height'].isna().to_list()
print(f"Null values = {null.count(True)}")

print(athletes_copy)

#################################################################
"""To be Done"""
#################################################################

Before fillna
Null values = 60171
After fillna
Null values = 60171
            ID                      Name Sex   Age  Height  Weight  \
0            1                 A Dijiang   M  24.0   180.0    80.0
1            2                  A Lamusi   M  23.0   170.0    60.0
2            3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN
3            4      Edgar Lindenau Aabye   M  34.0     NaN     NaN
4            5  Christine Jacoba Aaftink   F  21.0   185.0    82.0
...        ...                       ...  ..   ...     ...     ...
271111  135569                Andrzej ya   M  29.0   179.0    89.0
271112  135570                  Piotr ya   M  27.0   176.0    59.0
271113  135570                  Piotr ya   M  27.0   176.0    59.0
271114  135571        Tomasz Ireneusz ya   M  30.0   185.0    96.0
271115  135571        Tomasz Ireneusz ya   M  34.0   185.0    96.0

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona
1                China  CHN  2012 Summer  2012  Summer          London
2              Denmark  DEN  1920 Summer  1920  Summer       Antwerpen
3       Denmark/Sweden  DEN  1900 Summer  1900  Summer           Paris
4          Netherlands  NED  1988 Winter  1988  Winter         Calgary
...                ...  ...          ...   ...     ...             ...
271111        Poland-1  POL  1976 Winter  1976  Winter       Innsbruck
271112          Poland  POL  2014 Winter  2014  Winter           Sochi
271113          Poland  POL  2014 Winter  2014  Winter           Sochi
271114          Poland  POL  1998 Winter  1998  Winter          Nagano
271115          Poland  POL  2002 Winter  2002  Winter  Salt Lake City

                Sport                                     Event Medal
0          Basketball               Basketball Men's Basketball   NaN
1                Judo              Judo Men's Extra-Lightweight   NaN
2            Football                   Football Men's Football   NaN
3          Tug-Of-War               Tug-Of-War Men's Tug-Of-War  Gold
4       Speed Skating          Speed Skating Women's 500 metres   NaN
...               ...                                       ...   ...
271111           Luge                Luge Mixed (Men)'s Doubles   NaN
271112    Ski Jumping  Ski Jumping Men's Large Hill, Individual   NaN
271113    Ski Jumping        Ski Jumping Men's Large Hill, Team   NaN
271114      Bobsleigh                      Bobsleigh Men's Four   NaN
271115      Bobsleigh                      Bobsleigh Men's Four   NaN

[271116 rows x 15 columns]

In [ ]:
# Return total sales value per item
sales.head()
pd.read_sql(
    """SELECT item_name, SUM(CAST(REPLACE(item_price, '$', '') AS FLOAT)) AS total
    FROM sales_table
    GROUP BY item_name
    ORDER BY total DESC""", conn
)

                                item_name    total
0                            Chicken Bowl  7342.73
1                         Chicken Burrito  5575.82
2                           Steak Burrito  3851.43
3                              Steak Bowl  2260.19
4                     Chips and Guacamole  2201.04
5                      Chicken Salad Bowl  1228.75
6                      Chicken Soft Tacos  1108.09
7                          Veggie Burrito   934.77
8                        Barbacoa Burrito   894.75
9                             Veggie Bowl   867.99
10                          Carnitas Bowl   736.71
11                          Barbacoa Bowl   672.36
12                       Carnitas Burrito   597.83
13                       Steak Soft Tacos   536.05
14                                  Chips   494.34
15                   Chicken Crispy Tacos   472.13
16                      Canned Soft Drink   438.75
17                    Carnitas Soft Tacos   375.94
18           Chips and Fresh Tomato Salsa   361.36
19                     Steak Crispy Tacos   357.34
20                      6 Pack Soft Drink   356.95
21                       Steak Salad Bowl   343.59
22                          Bottled Water   302.56
23                    Barbacoa Soft Tacos   250.46
24                          Side of Chips   185.90
25                      Veggie Salad Bowl   182.50
26    Chips and Tomatillo Red Chili Salsa   147.50
27                            Canned Soda   137.34
28  Chips and Tomatillo Green Chili Salsa   132.75
29                  Barbacoa Crispy Tacos   120.21
30                    Barbacoa Salad Bowl   106.40
31                       Nantucket Nectar    98.31
32                          Chicken Salad    81.09
33  Chips and Tomatillo-Green Chili Salsa    78.87
34                  Carnitas Crispy Tacos    77.96
35                      Veggie Soft Tacos    73.96
36     Chips and Roasted Chili Corn Salsa    67.85
37                                   Izze    67.80
38                    Carnitas Salad Bowl    66.34
39    Chips and Tomatillo-Red Chili Salsa    59.75
40                           Veggie Salad    50.94
41                                Burrito    44.40
42     Chips and Roasted Chili-Corn Salsa    43.02
43                            Steak Salad    35.66
44                                   Bowl    29.60
45                                  Salad    14.80
46                           Crispy Tacos    14.80
47                         Carnitas Salad     8.99
48                    Veggie Crispy Tacos     8.49
49      Chips and Mild Fresh Tomato Salsa     3.00

In [83]:
# Show the top 5 records with the highest item_price
sales.head()

pd.read_sql(
    """SELECT * 
    FROM sales_table
    ORDER BY item_price DESC
    LIMIT 5""", conn
)

,order_id,quantity,item_name,choice_description,item_price
0,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$9.39
1,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
2,576,1,Barbacoa Salad Bowl,[Roasted Chili Corn Salsa],$9.39
3,738,1,Barbacoa Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$9.39
4,756,1,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$9.39

In [26]:
pd.read_sql(
    """SELECT * 
    FROM athletes_table
    LIMIT 10
    """, conn)

print(sales)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]

In [87]:
# How many unique customer orders are there (Assume each order_id is a customer)
sales.head()

pd.read_sql(
    """SELECT COUNT(DISTINCT order_id) AS customer_orders
    FROM sales_table
    """, conn
)

   customer_orders
0             1834

# Section 2
Write one query for this section.

Find countries with high-performing athletes in the Olympics. Use at least JOIN, NESTED QUERY, CASE, and optionally WITH.

For each country:

- Count the number of athletes who won at least one medal.
- Determine the average age of those medalists.
- Create a new column called performance:
    - 'High' if average age is below 25
    - 'Medium' if between 25 and 30
    - 'Low' if above 30